<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;
use App\Models\Lesson;
use App\Models\Kanji;
use App\Models\Card;

class DataKanjiSeeder extends Seeder
{
    public function run(): void
    {
        $course = Course::where('level', 'N5')->first();
        if (!$course) return;

        $lessons = [
            'N5.kanji_lesson1.title' => 1,
            'N5.kanji_lesson2.title' => 2,
            'N5.kanji_lesson3.title' => 3,
            'N5.kanji_lesson4.title' => 4,
            'N5.kanji_lesson5.title' => 5,
            'N5.kanji_lesson6.title' => 6,
            'N5.kanji_lesson7.title' => 7,
            'N5.kanji_lesson8.title' => 8,
            'N5.kanji_lesson9.title' => 9,
            'N5.kanji_lesson10.title' => 10,
        ];

        $lessonModels = [];
        foreach ($lessons as $titleKey => $index) {
            $lessonModels[$index] = Lesson::firstOrCreate(
                ['course_id' => $course->id, 'order_index' => $index, 'category' => 'kanji'],
                ['title' => $titleKey, 'is_published' => true]
            );
        }

        $kanjiLessons = [
            $lessonModels[1]->id => [
                ['character' => '一', 'sino_vietnamese' => 'N5.kanji_data.k1.sino', 'meaning' => 'N5.kanji_data.k1.meaning', 'onyomi' => ['イチ', 'イツ'], 'kunyomi' => ['ひと', 'ひと.つ'], 'stroke_count' => 1, 'mnemonic' => 'N5.kanji_data.k1.mnemonic', 'examples' => [['word' => '一つ', 'reading' => 'ひとつ', 'meaning' => 'N5.kanji_data.k1.ex1_meaning'], ['word' => '一日', 'reading' => 'ついたち', 'meaning' => 'N5.kanji_data.k1.ex2_meaning']]],
                ['character' => '二', 'sino_vietnamese' => 'N5.kanji_data.k2.sino', 'meaning' => 'N5.kanji_data.k2.meaning', 'onyomi' => ['ニ'], 'kunyomi' => ['ふた', 'ふた.つ'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k2.mnemonic', 'examples' => [['word' => '二つ', 'reading' => 'ふたつ', 'meaning' => 'N5.kanji_data.k2.ex1_meaning'], ['word' => '二月', 'reading' => 'にがつ', 'meaning' => 'N5.kanji_data.k2.ex2_meaning']]],
                ['character' => '三', 'sino_vietnamese' => 'N5.kanji_data.k3.sino', 'meaning' => 'N5.kanji_data.k3.meaning', 'onyomi' => ['サン'], 'kunyomi' => ['み', 'み.つ', 'みっ.つ'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k3.mnemonic', 'examples' => [['word' => '三つ', 'reading' => 'みっつ', 'meaning' => 'N5.kanji_data.k3.ex1_meaning'], ['word' => '三日', 'reading' => 'みっか', 'meaning' => 'N5.kanji_data.k3.ex2_meaning']]],
                ['character' => '四', 'sino_vietnamese' => 'N5.kanji_data.k4.sino', 'meaning' => 'N5.kanji_data.k4.meaning', 'onyomi' => ['シ'], 'kunyomi' => ['よ', 'よ.つ', 'よっ.つ', 'よん'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k4.mnemonic', 'examples' => [['word' => '四つ', 'reading' => 'よっつ', 'meaning' => 'N5.kanji_data.k4.ex1_meaning'], ['word' => '四月', 'reading' => 'しがつ', 'meaning' => 'N5.kanji_data.k4.ex2_meaning']]],
                ['character' => '五', 'sino_vietnamese' => 'N5.kanji_data.k5.sino', 'meaning' => 'N5.kanji_data.k5.meaning', 'onyomi' => ['ゴ'], 'kunyomi' => ['いつ', 'いつ.つ'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k5.mnemonic', 'examples' => [['word' => '五つ', 'reading' => 'いつつ', 'meaning' => 'N5.kanji_data.k5.ex1_meaning'], ['word' => '五日', 'reading' => 'いつか', 'meaning' => 'N5.kanji_data.k5.ex2_meaning']]],
                ['character' => '六', 'sino_vietnamese' => 'N5.kanji_data.k6.sino', 'meaning' => 'N5.kanji_data.k6.meaning', 'onyomi' => ['ロク'], 'kunyomi' => ['む', 'む.つ', 'むっ.つ', 'むい'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k6.mnemonic', 'examples' => [['word' => '六つ', 'reading' => 'むっつ', 'meaning' => 'N5.kanji_data.k6.ex1_meaning'], ['word' => '六日', 'reading' => 'むいか', 'meaning' => 'N5.kanji_data.k6.ex2_meaning']]],
                ['character' => '七', 'sino_vietnamese' => 'N5.kanji_data.k7.sino', 'meaning' => 'N5.kanji_data.k7.meaning', 'onyomi' => ['シチ'], 'kunyomi' => ['なな', 'なな.つ', 'なの'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k7.mnemonic', 'examples' => [['word' => '七つ', 'reading' => 'ななつ', 'meaning' => 'N5.kanji_data.k7.ex1_meaning'], ['word' => '七日', 'reading' => 'なのか', 'meaning' => 'N5.kanji_data.k7.ex2_meaning']]],
                ['character' => '八', 'sino_vietnamese' => 'N5.kanji_data.k8.sino', 'meaning' => 'N5.kanji_data.k8.meaning', 'onyomi' => ['ハチ'], 'kunyomi' => ['や', 'や.つ', 'やっ.つ', 'よう'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k8.mnemonic', 'examples' => [['word' => '八つ', 'reading' => 'やっつ', 'meaning' => 'N5.kanji_data.k8.ex1_meaning'], ['word' => '八日', 'reading' => 'ようか', 'meaning' => 'N5.kanji_data.k8.ex2_meaning']]],
                ['character' => '九', 'sino_vietnamese' => 'N5.kanji_data.k9.sino', 'meaning' => 'N5.kanji_data.k9.meaning', 'onyomi' => ['キュウ', 'ク'], 'kunyomi' => ['ここの', 'ここの.つ'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k9.mnemonic', 'examples' => [['word' => '九つ', 'reading' => 'ここのつ', 'meaning' => 'N5.kanji_data.k9.ex1_meaning'], ['word' => '九日', 'reading' => 'ここのか', 'meaning' => 'N5.kanji_data.k9.ex2_meaning']]],
                ['character' => '十', 'sino_vietnamese' => 'N5.kanji_data.k10.sino', 'meaning' => 'N5.kanji_data.k10.meaning', 'onyomi' => ['ジュウ', 'ジッ', 'ジュッ'], 'kunyomi' => ['とお', 'と'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k10.mnemonic', 'examples' => [['word' => '十', 'reading' => 'とお', 'meaning' => 'N5.kanji_data.k10.ex1_meaning'], ['word' => '十日', 'reading' => 'とおか', 'meaning' => 'N5.kanji_data.k10.ex2_meaning']]],
            ],
            $lessonModels[2]->id => [
                ['character' => '百', 'sino_vietnamese' => 'N5.kanji_data.k11.sino', 'meaning' => 'N5.kanji_data.k11.meaning', 'onyomi' => ['ヒャク'], 'kunyomi' => ['もも'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k11.mnemonic', 'examples' => [['word' => '百', 'reading' => 'ひゃく', 'meaning' => 'N5.kanji_data.k11.ex1_meaning'], ['word' => '三百', 'reading' => 'さんびゃく', 'meaning' => 'N5.kanji_data.k11.ex2_meaning']]],
                ['character' => '千', 'sino_vietnamese' => 'N5.kanji_data.k12.sino', 'meaning' => 'N5.kanji_data.k12.meaning', 'onyomi' => ['セン'], 'kunyomi' => ['ち'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k12.mnemonic', 'examples' => [['word' => '千', 'reading' => 'せん', 'meaning' => 'N5.kanji_data.k12.ex1_meaning'], ['word' => '三千', 'reading' => 'さんぜん', 'meaning' => 'N5.kanji_data.k12.ex2_meaning']]],
                ['character' => '万', 'sino_vietnamese' => 'N5.kanji_data.k13.sino', 'meaning' => 'N5.kanji_data.k13.meaning', 'onyomi' => ['マン', 'バン'], 'kunyomi' => [], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k13.mnemonic', 'examples' => [['word' => '一万', 'reading' => 'いちまん', 'meaning' => 'N5.kanji_data.k13.ex1_meaning'], ['word' => '万年筆', 'reading' => 'まんねんひつ', 'meaning' => 'N5.kanji_data.k13.ex2_meaning']]],
                ['character' => '円', 'sino_vietnamese' => 'N5.kanji_data.k14.sino', 'meaning' => 'N5.kanji_data.k14.meaning', 'onyomi' => ['エン'], 'kunyomi' => ['まる.い', 'まる'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k14.mnemonic', 'examples' => [['word' => '百円', 'reading' => 'ひゃくえん', 'meaning' => 'N5.kanji_data.k14.ex1_meaning'], ['word' => '円い', 'reading' => 'まるい', 'meaning' => 'N5.kanji_data.k14.ex2_meaning']]],
                ['character' => '年', 'sino_vietnamese' => 'N5.kanji_data.k15.sino', 'meaning' => 'N5.kanji_data.k15.meaning', 'onyomi' => ['ネン'], 'kunyomi' => ['とし'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k15.mnemonic', 'examples' => [['word' => '今年', 'reading' => 'ことし', 'meaning' => 'N5.kanji_data.k15.ex1_meaning'], ['word' => '来年', 'reading' => 'らいねん', 'meaning' => 'N5.kanji_data.k15.ex2_meaning']]],
                ['character' => '今', 'sino_vietnamese' => 'N5.kanji_data.k16.sino', 'meaning' => 'N5.kanji_data.k16.meaning', 'onyomi' => ['コン', 'キン'], 'kunyomi' => ['いま'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k16.mnemonic', 'examples' => [['word' => '今', 'reading' => 'いま', 'meaning' => 'N5.kanji_data.k16.ex1_meaning'], ['word' => '今日', 'reading' => 'きょう', 'meaning' => 'N5.kanji_data.k16.ex2_meaning']]],
                ['character' => '時', 'sino_vietnamese' => 'N5.kanji_data.k17.sino', 'meaning' => 'N5.kanji_data.k17.meaning', 'onyomi' => ['ジ'], 'kunyomi' => ['とき'], 'stroke_count' => 10, 'mnemonic' => 'N5.kanji_data.k17.mnemonic', 'examples' => [['word' => '時計', 'reading' => 'とけい', 'meaning' => 'N5.kanji_data.k17.ex1_meaning'], ['word' => '九時', 'reading' => 'くじ', 'meaning' => 'N5.kanji_data.k17.ex2_meaning']]],
                ['character' => '半', 'sino_vietnamese' => 'N5.kanji_data.k18.sino', 'meaning' => 'N5.kanji_data.k18.meaning', 'onyomi' => ['ハン'], 'kunyomi' => ['なか.ば'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k18.mnemonic', 'examples' => [['word' => '半分', 'reading' => 'はんぶん', 'meaning' => 'N5.kanji_data.k18.ex1_meaning'], ['word' => '一時半', 'reading' => 'いちじはん', 'meaning' => 'N5.kanji_data.k18.ex2_meaning']]],
                ['character' => '分', 'sino_vietnamese' => 'N5.kanji_data.k19.sino', 'meaning' => 'N5.kanji_data.k19.meaning', 'onyomi' => ['ブン', 'フン', 'ブ'], 'kunyomi' => ['わ.かる', 'わ.ける'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k19.mnemonic', 'examples' => [['word' => '分かる', 'reading' => 'わかる', 'meaning' => 'N5.kanji_data.k19.ex1_meaning'], ['word' => '五分', 'reading' => 'ごふん', 'meaning' => 'N5.kanji_data.k19.ex2_meaning']]],
                ['character' => '曜', 'sino_vietnamese' => 'N5.kanji_data.k20.sino', 'meaning' => 'N5.kanji_data.k20.meaning', 'onyomi' => ['ヨウ'], 'kunyomi' => [], 'stroke_count' => 18, 'mnemonic' => 'N5.kanji_data.k20.mnemonic', 'examples' => [['word' => '日曜日', 'reading' => 'にちようび', 'meaning' => 'N5.kanji_data.k20.ex1_meaning'], ['word' => '月曜日', 'reading' => 'げつようび', 'meaning' => 'N5.kanji_data.k20.ex2_meaning']]],
                ['character' => '毎', 'sino_vietnamese' => 'N5.kanji_data.k21.sino', 'meaning' => 'N5.kanji_data.k21.meaning', 'onyomi' => ['マイ'], 'kunyomi' => ['ごと'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k21.mnemonic', 'examples' => [['word' => '毎日', 'reading' => 'まいにち', 'meaning' => 'N5.kanji_data.k21.ex1_meaning'], ['word' => '毎年', 'reading' => 'まいとし', 'meaning' => 'N5.kanji_data.k21.ex2_meaning']]],
            ],
            $lessonModels[3]->id => [
                ['character' => '日', 'sino_vietnamese' => 'N5.kanji_data.k22.sino', 'meaning' => 'N5.kanji_data.k22.meaning', 'onyomi' => ['ニチ', 'ジツ'], 'kunyomi' => ['ひ', 'び', 'か'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k22.mnemonic', 'examples' => [['word' => '日本', 'reading' => 'にほん', 'meaning' => 'N5.kanji_data.k22.ex1_meaning'], ['word' => '休日', 'reading' => 'きゅうじつ', 'meaning' => 'N5.kanji_data.k22.ex2_meaning']]],
                ['character' => '月', 'sino_vietnamese' => 'N5.kanji_data.k23.sino', 'meaning' => 'N5.kanji_data.k23.meaning', 'onyomi' => ['ゲツ', 'ガツ'], 'kunyomi' => ['つき'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k23.mnemonic', 'examples' => [['word' => '月', 'reading' => 'つき', 'meaning' => 'N5.kanji_data.k23.ex1_meaning'], ['word' => '一月', 'reading' => 'いちがつ', 'meaning' => 'N5.kanji_data.k23.ex2_meaning']]],
                ['character' => '木', 'sino_vietnamese' => 'N5.kanji_data.k24.sino', 'meaning' => 'N5.kanji_data.k24.meaning', 'onyomi' => ['ボク', 'モク'], 'kunyomi' => ['き', 'こ'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k24.mnemonic', 'examples' => [['word' => '木', 'reading' => 'き', 'meaning' => 'N5.kanji_data.k24.ex1_meaning'], ['word' => '木曜日', 'reading' => 'もくようび', 'meaning' => 'N5.kanji_data.k24.ex2_meaning']]],
                ['character' => '水', 'sino_vietnamese' => 'N5.kanji_data.k25.sino', 'meaning' => 'N5.kanji_data.k25.meaning', 'onyomi' => ['スイ'], 'kunyomi' => ['みず'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k25.mnemonic', 'examples' => [['word' => '水', 'reading' => 'みず', 'meaning' => 'N5.kanji_data.k25.ex1_meaning'], ['word' => '水曜日', 'reading' => 'すいようび', 'meaning' => 'N5.kanji_data.k25.ex2_meaning']]],
                ['character' => '火', 'sino_vietnamese' => 'N5.kanji_data.k26.sino', 'meaning' => 'N5.kanji_data.k26.meaning', 'onyomi' => ['カ'], 'kunyomi' => ['ひ', 'び', 'ほ'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k26.mnemonic', 'examples' => [['word' => '火', 'reading' => 'ひ', 'meaning' => 'N5.kanji_data.k26.ex1_meaning'], ['word' => '火曜日', 'reading' => 'かようび', 'meaning' => 'N5.kanji_data.k26.ex2_meaning']]],
                ['character' => '金', 'sino_vietnamese' => 'N5.kanji_data.k27.sino', 'meaning' => 'N5.kanji_data.k27.meaning', 'onyomi' => ['キン', 'コン'], 'kunyomi' => ['かね', 'かな'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k27.mnemonic', 'examples' => [['word' => 'お金', 'reading' => 'おかね', 'meaning' => 'N5.kanji_data.k27.ex1_meaning'], ['word' => '金曜日', 'reading' => 'きんようび', 'meaning' => 'N5.kanji_data.k27.ex2_meaning']]],
                ['character' => '土', 'sino_vietnamese' => 'N5.kanji_data.k28.sino', 'meaning' => 'N5.kanji_data.k28.meaning', 'onyomi' => ['ド', 'ト'], 'kunyomi' => ['つち'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k28.mnemonic', 'examples' => [['word' => '土', 'reading' => 'つち', 'meaning' => 'N5.kanji_data.k28.ex1_meaning'], ['word' => '土曜日', 'reading' => 'どようび', 'meaning' => 'N5.kanji_data.k28.ex2_meaning']]],
                ['character' => '山', 'sino_vietnamese' => 'N5.kanji_data.k29.sino', 'meaning' => 'N5.kanji_data.k29.meaning', 'onyomi' => ['サン'], 'kunyomi' => ['やま'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k29.mnemonic', 'examples' => [['word' => '山', 'reading' => 'やま', 'meaning' => 'N5.kanji_data.k29.ex1_meaning'], ['word' => '富士山', 'reading' => 'ふじさん', 'meaning' => 'N5.kanji_data.k29.ex2_meaning']]],
                ['character' => '川', 'sino_vietnamese' => 'N5.kanji_data.k30.sino', 'meaning' => 'N5.kanji_data.k30.meaning', 'onyomi' => ['セン'], 'kunyomi' => ['かわ'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k30.mnemonic', 'examples' => [['word' => '川', 'reading' => 'かわ', 'meaning' => 'N5.kanji_data.k30.ex1_meaning'], ['word' => '小川', 'reading' => 'おがわ', 'meaning' => 'N5.kanji_data.k30.ex2_meaning']]],
                ['character' => '田', 'sino_vietnamese' => 'N5.kanji_data.k31.sino', 'meaning' => 'N5.kanji_data.k31.meaning', 'onyomi' => ['デン'], 'kunyomi' => ['た'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k31.mnemonic', 'examples' => [['word' => '田んぼ', 'reading' => 'たんぼ', 'meaning' => 'N5.kanji_data.k31.ex1_meaning'], ['word' => '水田', 'reading' => 'すいでん', 'meaning' => 'N5.kanji_data.k31.ex2_meaning']]],
            ],
            $lessonModels[4]->id => [
                ['character' => '空', 'sino_vietnamese' => 'N5.kanji_data.k32.sino', 'meaning' => 'N5.kanji_data.k32.meaning', 'onyomi' => ['クウ'], 'kunyomi' => ['そら', 'あ.く', 'から'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k32.mnemonic', 'examples' => [['word' => '空', 'reading' => 'そら', 'meaning' => 'N5.kanji_data.k32.ex1_meaning'], ['word' => '空気', 'reading' => 'くうき', 'meaning' => 'N5.kanji_data.k32.ex2_meaning']]],
                ['character' => '天', 'sino_vietnamese' => 'N5.kanji_data.k33.sino', 'meaning' => 'N5.kanji_data.k33.meaning', 'onyomi' => ['テン'], 'kunyomi' => ['あめ', 'あま'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k33.mnemonic', 'examples' => [['word' => '天気', 'reading' => 'てんき', 'meaning' => 'N5.kanji_data.k33.ex1_meaning'], ['word' => '天国', 'reading' => 'てんごく', 'meaning' => 'N5.kanji_data.k33.ex2_meaning']]],
                ['character' => '気', 'sino_vietnamese' => 'N5.kanji_data.k34.sino', 'meaning' => 'N5.kanji_data.k34.meaning', 'onyomi' => ['キ', 'ケ'], 'kunyomi' => ['いき'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k34.mnemonic', 'examples' => [['word' => '元気', 'reading' => 'げんき', 'meaning' => 'N5.kanji_data.k34.ex1_meaning'], ['word' => '気持ち', 'reading' => 'きもち', 'meaning' => 'N5.kanji_data.k34.ex2_meaning']]],
                ['character' => '雨', 'sino_vietnamese' => 'N5.kanji_data.k35.sino', 'meaning' => 'N5.kanji_data.k35.meaning', 'onyomi' => ['ウ'], 'kunyomi' => ['あめ', 'あま'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k35.mnemonic', 'examples' => [['word' => '雨', 'reading' => 'あめ', 'meaning' => 'N5.kanji_data.k35.ex1_meaning'], ['word' => '大雨', 'reading' => 'おおあめ', 'meaning' => 'N5.kanji_data.k35.ex2_meaning']]],
                ['character' => '白', 'sino_vietnamese' => 'N5.kanji_data.k36.sino', 'meaning' => 'N5.kanji_data.k36.meaning', 'onyomi' => ['ハク'], 'kunyomi' => ['しろ', 'しろ.い'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k36.mnemonic', 'examples' => [['word' => '白い', 'reading' => 'しろい', 'meaning' => 'N5.kanji_data.k36.ex1_meaning'], ['word' => '白黒', 'reading' => 'しろくろ', 'meaning' => 'N5.kanji_data.k36.ex2_meaning']]],
                ['character' => '黒', 'sino_vietnamese' => 'N5.kanji_data.k37.sino', 'meaning' => 'N5.kanji_data.k37.meaning', 'onyomi' => ['コク'], 'kunyomi' => ['くろ', 'くろ.い'], 'stroke_count' => 11, 'mnemonic' => 'N5.kanji_data.k37.mnemonic', 'examples' => [['word' => '黒い', 'reading' => 'くろい', 'meaning' => 'N5.kanji_data.k37.ex1_meaning'], ['word' => '真っ黒', 'reading' => 'まっくろ', 'meaning' => 'N5.kanji_data.k37.ex2_meaning']]],
                ['character' => '赤', 'sino_vietnamese' => 'N5.kanji_data.k38.sino', 'meaning' => 'N5.kanji_data.k38.meaning', 'onyomi' => ['セキ', 'シャク'], 'kunyomi' => ['あか', 'あか.い'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k38.mnemonic', 'examples' => [['word' => '赤い', 'reading' => 'あかい', 'meaning' => 'N5.kanji_data.k38.ex1_meaning'], ['word' => '赤ちゃん', 'reading' => 'あかちゃん', 'meaning' => 'N5.kanji_data.k38.ex2_meaning']]],
                ['character' => '青', 'sino_vietnamese' => 'N5.kanji_data.k39.sino', 'meaning' => 'N5.kanji_data.k39.meaning', 'onyomi' => ['セイ', 'ショウ'], 'kunyomi' => ['あお', 'あお.い'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k39.mnemonic', 'examples' => [['word' => '青い', 'reading' => 'あおい', 'meaning' => 'N5.kanji_data.k39.ex1_meaning'], ['word' => '青年', 'reading' => 'せいねん', 'meaning' => 'N5.kanji_data.k39.ex2_meaning']]],
                ['character' => '多', 'sino_vietnamese' => 'N5.kanji_data.k40.sino', 'meaning' => 'N5.kanji_data.k40.meaning', 'onyomi' => ['タ'], 'kunyomi' => ['おお.い'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k40.mnemonic', 'examples' => [['word' => '多い', 'reading' => 'おおい', 'meaning' => 'N5.kanji_data.k40.ex1_meaning'], ['word' => '多分', 'reading' => 'たぶん', 'meaning' => 'N5.kanji_data.k40.ex2_meaning']]],
                ['character' => '少', 'sino_vietnamese' => 'N5.kanji_data.k41.sino', 'meaning' => 'N5.kanji_data.k41.meaning', 'onyomi' => ['ショウ'], 'kunyomi' => ['すく.ない', 'すこ.し'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k41.mnemonic', 'examples' => [['word' => '少ない', 'reading' => 'すくない', 'meaning' => 'N5.kanji_data.k41.ex1_meaning'], ['word' => '少し', 'reading' => 'すこし', 'meaning' => 'N5.kanji_data.k41.ex2_meaning']]],
            ],
            $lessonModels[5]->id => [
                ['character' => '人', 'sino_vietnamese' => 'N5.kanji_data.k42.sino', 'meaning' => 'N5.kanji_data.k42.meaning', 'onyomi' => ['ジン', 'ニン'], 'kunyomi' => ['ひと'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k42.mnemonic', 'examples' => [['word' => '人', 'reading' => 'ひと', 'meaning' => 'N5.kanji_data.k42.ex1_meaning'], ['word' => '日本人', 'reading' => 'にほんじん', 'meaning' => 'N5.kanji_data.k42.ex2_meaning']]],
                ['character' => '子', 'sino_vietnamese' => 'N5.kanji_data.k43.sino', 'meaning' => 'N5.kanji_data.k43.meaning', 'onyomi' => ['シ', 'ス'], 'kunyomi' => ['こ'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k43.mnemonic', 'examples' => [['word' => '子ども', 'reading' => 'こども', 'meaning' => 'N5.kanji_data.k43.ex1_meaning'], ['word' => '男の子', 'reading' => 'おとこのこ', 'meaning' => 'N5.kanji_data.k43.ex2_meaning']]],
                ['character' => '女', 'sino_vietnamese' => 'N5.kanji_data.k44.sino', 'meaning' => 'N5.kanji_data.k44.meaning', 'onyomi' => ['ジョ', 'ニョ', 'ニョウ'], 'kunyomi' => ['おんな', 'め'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k44.mnemonic', 'examples' => [['word' => '女の人', 'reading' => 'おんなのひと', 'meaning' => 'N5.kanji_data.k44.ex1_meaning'], ['word' => '彼女', 'reading' => 'かのじょ', 'meaning' => 'N5.kanji_data.k44.ex2_meaning']]],
                ['character' => '男', 'sino_vietnamese' => 'N5.kanji_data.k45.sino', 'meaning' => 'N5.kanji_data.k45.meaning', 'onyomi' => ['ダン', 'ナン'], 'kunyomi' => ['おとこ'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k45.mnemonic', 'examples' => [['word' => '男の人', 'reading' => 'おとこのひと', 'meaning' => 'N5.kanji_data.k45.ex1_meaning'], ['word' => '男子', 'reading' => 'だんし', 'meaning' => 'N5.kanji_data.k45.ex2_meaning']]],
                ['character' => '父', 'sino_vietnamese' => 'N5.kanji_data.k46.sino', 'meaning' => 'N5.kanji_data.k46.meaning', 'onyomi' => ['フ'], 'kunyomi' => ['ちち'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k46.mnemonic', 'examples' => [['word' => '父', 'reading' => 'ちち', 'meaning' => 'N5.kanji_data.k46.ex1_meaning'], ['word' => 'お父さん', 'reading' => 'おとうさん', 'meaning' => 'N5.kanji_data.k46.ex2_meaning']]],
                ['character' => '母', 'sino_vietnamese' => 'N5.kanji_data.k47.sino', 'meaning' => 'N5.kanji_data.k47.meaning', 'onyomi' => ['ボ'], 'kunyomi' => ['はは'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k47.mnemonic', 'examples' => [['word' => '母', 'reading' => 'はは', 'meaning' => 'N5.kanji_data.k47.ex1_meaning'], ['word' => 'お母さん', 'reading' => 'おかあさん', 'meaning' => 'N5.kanji_data.k47.ex2_meaning']]],
                ['character' => '友', 'sino_vietnamese' => 'N5.kanji_data.k48.sino', 'meaning' => 'N5.kanji_data.k48.meaning', 'onyomi' => ['ユウ'], 'kunyomi' => ['とも'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k48.mnemonic', 'examples' => [['word' => '友だち', 'reading' => 'ともだち', 'meaning' => 'N5.kanji_data.k48.ex1_meaning'], ['word' => '親友', 'reading' => 'しんゆう', 'meaning' => 'N5.kanji_data.k48.ex2_meaning']]],
                ['character' => '私', 'sino_vietnamese' => 'N5.kanji_data.k49.sino', 'meaning' => 'N5.kanji_data.k49.meaning', 'onyomi' => ['シ'], 'kunyomi' => ['わたし', 'わたくし'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k49.mnemonic', 'examples' => [['word' => '私', 'reading' => 'わたし', 'meaning' => 'N5.kanji_data.k49.ex1_meaning'], ['word' => '私たち', 'reading' => 'わたしたち', 'meaning' => 'N5.kanji_data.k49.ex2_meaning']]],
                ['character' => '先', 'sino_vietnamese' => 'N5.kanji_data.k50.sino', 'meaning' => 'N5.kanji_data.k50.meaning', 'onyomi' => ['セン'], 'kunyomi' => ['さき', 'まず'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k50.mnemonic', 'examples' => [['word' => '先生', 'reading' => 'せんせい', 'meaning' => 'N5.kanji_data.k50.ex1_meaning'], ['word' => '先月', 'reading' => 'せんげつ', 'meaning' => 'N5.kanji_data.k50.ex2_meaning']]],
                ['character' => '生', 'sino_vietnamese' => 'N5.kanji_data.k51.sino', 'meaning' => 'N5.kanji_data.k51.meaning', 'onyomi' => ['セイ', 'ショウ'], 'kunyomi' => ['い.きる', 'う.まれる', 'なま'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k51.mnemonic', 'examples' => [['word' => '学生', 'reading' => 'がくせい', 'meaning' => 'N5.kanji_data.k51.ex1_meaning'], ['word' => '生まれる', 'reading' => 'うまれる', 'meaning' => 'N5.kanji_data.k51.ex2_meaning']]],
            ],
            $lessonModels[6]->id => [
                ['character' => '目', 'sino_vietnamese' => 'N5.kanji_data.k52.sino', 'meaning' => 'N5.kanji_data.k52.meaning', 'onyomi' => ['モク', 'ボク'], 'kunyomi' => ['め', 'ま'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k52.mnemonic', 'examples' => [['word' => '目', 'reading' => 'め', 'meaning' => 'N5.kanji_data.k52.ex1_meaning'], ['word' => '目薬', 'reading' => 'めぐすり', 'meaning' => 'N5.kanji_data.k52.ex2_meaning']]],
                ['character' => '耳', 'sino_vietnamese' => 'N5.kanji_data.k53.sino', 'meaning' => 'N5.kanji_data.k53.meaning', 'onyomi' => ['ジ'], 'kunyomi' => ['みみ'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k53.mnemonic', 'examples' => [['word' => '耳', 'reading' => 'みみ', 'meaning' => 'N5.kanji_data.k53.ex1_meaning'], ['word' => '耳鼻科', 'reading' => 'じびか', 'meaning' => 'N5.kanji_data.k53.ex2_meaning']]],
                ['character' => '口', 'sino_vietnamese' => 'N5.kanji_data.k54.sino', 'meaning' => 'N5.kanji_data.k54.meaning', 'onyomi' => ['コウ', 'ク'], 'kunyomi' => ['くち'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k54.mnemonic', 'examples' => [['word' => '口', 'reading' => 'くち', 'meaning' => 'N5.kanji_data.k54.ex1_meaning'], ['word' => '入口', 'reading' => 'いりぐち', 'meaning' => 'N5.kanji_data.k54.ex2_meaning']]],
                ['character' => '手', 'sino_vietnamese' => 'N5.kanji_data.k55.sino', 'meaning' => 'N5.kanji_data.k55.meaning', 'onyomi' => ['シュ', 'ズ'], 'kunyomi' => ['て', 'た'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k55.mnemonic', 'examples' => [['word' => '手', 'reading' => 'て', 'meaning' => 'N5.kanji_data.k55.ex1_meaning'], ['word' => '上手', 'reading' => 'じょうず', 'meaning' => 'N5.kanji_data.k55.ex2_meaning']]],
                ['character' => '足', 'sino_vietnamese' => 'N5.kanji_data.k56.sino', 'meaning' => 'N5.kanji_data.k56.meaning', 'onyomi' => ['ソク'], 'kunyomi' => ['あし', 'た.りる', 'た.す'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k56.mnemonic', 'examples' => [['word' => '足', 'reading' => 'あし', 'meaning' => 'N5.kanji_data.k56.ex1_meaning'], ['word' => '足りる', 'reading' => 'たりる', 'meaning' => 'N5.kanji_data.k56.ex2_meaning']]],
                ['character' => '力', 'sino_vietnamese' => 'N5.kanji_data.k57.sino', 'meaning' => 'N5.kanji_data.k57.meaning', 'onyomi' => ['リョク', 'リキ'], 'kunyomi' => ['ちから'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k57.mnemonic', 'examples' => [['word' => '力', 'reading' => 'ちから', 'meaning' => 'N5.kanji_data.k57.ex1_meaning'], ['word' => '努力', 'reading' => 'どりょく', 'meaning' => 'N5.kanji_data.k57.ex2_meaning']]],
                ['character' => '見', 'sino_vietnamese' => 'N5.kanji_data.k58.sino', 'meaning' => 'N5.kanji_data.k58.meaning', 'onyomi' => ['ケン'], 'kunyomi' => ['み.る', 'み.える', 'み.せる'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k58.mnemonic', 'examples' => [['word' => '見る', 'reading' => 'みる', 'meaning' => 'N5.kanji_data.k58.ex1_meaning'], ['word' => '見せる', 'reading' => 'みせる', 'meaning' => 'N5.kanji_data.k58.ex2_meaning']]],
                ['character' => '聞', 'sino_vietnamese' => 'N5.kanji_data.k59.sino', 'meaning' => 'N5.kanji_data.k59.meaning', 'onyomi' => ['ブン', 'モン'], 'kunyomi' => ['き.く', 'き.こえる'], 'stroke_count' => 14, 'mnemonic' => 'N5.kanji_data.k59.mnemonic', 'examples' => [['word' => '聞く', 'reading' => 'きく', 'meaning' => 'N5.kanji_data.k59.ex1_meaning'], ['word' => '新聞', 'reading' => 'しんぶん', 'meaning' => 'N5.kanji_data.k59.ex2_meaning']]],
                ['character' => '言', 'sino_vietnamese' => 'N5.kanji_data.k60.sino', 'meaning' => 'N5.kanji_data.k60.meaning', 'onyomi' => ['ゲン', 'ゴン'], 'kunyomi' => ['い.う', 'こと'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k60.mnemonic', 'examples' => [['word' => '言う', 'reading' => 'いう', 'meaning' => 'N5.kanji_data.k60.ex1_meaning'], ['word' => '言葉', 'reading' => 'ことば', 'meaning' => 'N5.kanji_data.k60.ex2_meaning']]],
                ['character' => '話', 'sino_vietnamese' => 'N5.kanji_data.k61.sino', 'meaning' => 'N5.kanji_data.k61.meaning', 'onyomi' => ['ワ'], 'kunyomi' => ['はな.す', 'はなし'], 'stroke_count' => 13, 'mnemonic' => 'N5.kanji_data.k61.mnemonic', 'examples' => [['word' => '話す', 'reading' => 'はなす', 'meaning' => 'N5.kanji_data.k61.ex1_meaning'], ['word' => '電話', 'reading' => 'でんわ', 'meaning' => 'N5.kanji_data.k61.ex2_meaning']]],
            ],
            $lessonModels[7]->id => [
                ['character' => '上', 'sino_vietnamese' => 'N5.kanji_data.k62.sino', 'meaning' => 'N5.kanji_data.k62.meaning', 'onyomi' => ['ジョウ'], 'kunyomi' => ['うえ', 'あ.がる'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k62.mnemonic', 'examples' => [['word' => '上', 'reading' => 'うえ', 'meaning' => 'N5.kanji_data.k62.ex1_meaning'], ['word' => '上がる', 'reading' => 'あがる', 'meaning' => 'N5.kanji_data.k62.ex2_meaning']]],
                ['character' => '下', 'sino_vietnamese' => 'N5.kanji_data.k63.sino', 'meaning' => 'N5.kanji_data.k63.meaning', 'onyomi' => ['カ', 'ゲ'], 'kunyomi' => ['した', 'さ.がる'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k63.mnemonic', 'examples' => [['word' => '下', 'reading' => 'した', 'meaning' => 'N5.kanji_data.k63.ex1_meaning'], ['word' => '下がる', 'reading' => 'さがる', 'meaning' => 'N5.kanji_data.k63.ex2_meaning']]],
                ['character' => '左', 'sino_vietnamese' => 'N5.kanji_data.k64.sino', 'meaning' => 'N5.kanji_data.k64.meaning', 'onyomi' => ['サ'], 'kunyomi' => ['ひだり'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k64.mnemonic', 'examples' => [['word' => '左', 'reading' => 'ひだり', 'meaning' => 'N5.kanji_data.k64.ex1_meaning'], ['word' => '左手', 'reading' => 'ひだりて', 'meaning' => 'N5.kanji_data.k64.ex2_meaning']]],
                ['character' => '右', 'sino_vietnamese' => 'N5.kanji_data.k65.sino', 'meaning' => 'N5.kanji_data.k65.meaning', 'onyomi' => ['ユウ', 'ウ'], 'kunyomi' => ['みぎ'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k65.mnemonic', 'examples' => [['word' => '右', 'reading' => 'みぎ', 'meaning' => 'N5.kanji_data.k65.ex1_meaning'], ['word' => '右手', 'reading' => 'みぎて', 'meaning' => 'N5.kanji_data.k65.ex2_meaning']]],
                ['character' => '中', 'sino_vietnamese' => 'N5.kanji_data.k66.sino', 'meaning' => 'N5.kanji_data.k66.meaning', 'onyomi' => ['チュウ'], 'kunyomi' => ['なか'], 'stroke_count' => 4, 'mnemonic' => 'N5.kanji_data.k66.mnemonic', 'examples' => [['word' => '中', 'reading' => 'なか', 'meaning' => 'N5.kanji_data.k66.ex1_meaning'], ['word' => '中国', 'reading' => 'ちゅうごく', 'meaning' => 'N5.kanji_data.k66.ex2_meaning']]],
                ['character' => '外', 'sino_vietnamese' => 'N5.kanji_data.k67.sino', 'meaning' => 'N5.kanji_data.k67.meaning', 'onyomi' => ['ガイ', 'ゲ'], 'kunyomi' => ['そと', 'ほか', 'はず.す'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k67.mnemonic', 'examples' => [['word' => '外', 'reading' => 'そと', 'meaning' => 'N5.kanji_data.k67.ex1_meaning'], ['word' => '外国人', 'reading' => 'がいこくじん', 'meaning' => 'N5.kanji_data.k67.ex2_meaning']]],
                ['character' => '前', 'sino_vietnamese' => 'N5.kanji_data.k68.sino', 'meaning' => 'N5.kanji_data.k68.meaning', 'onyomi' => ['ゼン'], 'kunyomi' => ['まえ'], 'stroke_count' => 9, 'mnemonic' => 'N5.kanji_data.k68.mnemonic', 'examples' => [['word' => '前', 'reading' => 'まえ', 'meaning' => 'N5.kanji_data.k68.ex1_meaning'], ['word' => '午前', 'reading' => 'ごぜん', 'meaning' => 'N5.kanji_data.k68.ex2_meaning']]],
                ['character' => '後', 'sino_vietnamese' => 'N5.kanji_data.k69.sino', 'meaning' => 'N5.kanji_data.k69.meaning', 'onyomi' => ['ゴ', 'コウ'], 'kunyomi' => ['あと', 'うし.ろ', 'のち'], 'stroke_count' => 9, 'mnemonic' => 'N5.kanji_data.k69.mnemonic', 'examples' => [['word' => '後ろ', 'reading' => 'うしろ', 'meaning' => 'N5.kanji_data.k69.ex1_meaning'], ['word' => '午後', 'reading' => 'ごご', 'meaning' => 'N5.kanji_data.k69.ex2_meaning']]],
                ['character' => '東', 'sino_vietnamese' => 'N5.kanji_data.k70.sino', 'meaning' => 'N5.kanji_data.k70.meaning', 'onyomi' => ['トウ'], 'kunyomi' => ['ひがし'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k70.mnemonic', 'examples' => [['word' => '東', 'reading' => 'ひがし', 'meaning' => 'N5.kanji_data.k70.ex1_meaning'], ['word' => '東京', 'reading' => 'とうきょう', 'meaning' => 'N5.kanji_data.k70.ex2_meaning']]],
                ['character' => '西', 'sino_vietnamese' => 'N5.kanji_data.k71.sino', 'meaning' => 'N5.kanji_data.k71.meaning', 'onyomi' => ['セイ', 'サイ'], 'kunyomi' => ['にし'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k71.mnemonic', 'examples' => [['word' => '西', 'reading' => 'にし', 'meaning' => 'N5.kanji_data.k71.ex1_meaning'], ['word' => '西洋', 'reading' => 'せいよう', 'meaning' => 'N5.kanji_data.k71.ex2_meaning']]],
            ],
            $lessonModels[8]->id => [
                ['character' => '大', 'sino_vietnamese' => 'N5.kanji_data.k72.sino', 'meaning' => 'N5.kanji_data.k72.meaning', 'onyomi' => ['ダイ', 'タイ'], 'kunyomi' => ['おお.きい'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k72.mnemonic', 'examples' => [['word' => '大きい', 'reading' => 'おおきい', 'meaning' => 'N5.kanji_data.k72.ex1_meaning'], ['word' => '大学', 'reading' => 'だいがく', 'meaning' => 'N5.kanji_data.k72.ex2_meaning']]],
                ['character' => '小', 'sino_vietnamese' => 'N5.kanji_data.k73.sino', 'meaning' => 'N5.kanji_data.k73.meaning', 'onyomi' => ['ショウ'], 'kunyomi' => ['ちい.さい', 'こ', 'お'], 'stroke_count' => 3, 'mnemonic' => 'N5.kanji_data.k73.mnemonic', 'examples' => [['word' => '小さい', 'reading' => 'ちいさい', 'meaning' => 'N5.kanji_data.k73.ex1_meaning'], ['word' => '小学校', 'reading' => 'しょうがっこう', 'meaning' => 'N5.kanji_data.k73.ex2_meaning']]],
                ['character' => '高', 'sino_vietnamese' => 'N5.kanji_data.k74.sino', 'meaning' => 'N5.kanji_data.k74.meaning', 'onyomi' => ['コウ'], 'kunyomi' => ['たか.い'], 'stroke_count' => 10, 'mnemonic' => 'N5.kanji_data.k74.mnemonic', 'examples' => [['word' => '高い', 'reading' => 'たかい', 'meaning' => 'N5.kanji_data.k74.ex1_meaning'], ['word' => '高校', 'reading' => 'こうこう', 'meaning' => 'N5.kanji_data.k74.ex2_meaning']]],
                ['character' => '安', 'sino_vietnamese' => 'N5.kanji_data.k75.sino', 'meaning' => 'N5.kanji_data.k75.meaning', 'onyomi' => ['アン'], 'kunyomi' => ['やす.い'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k75.mnemonic', 'examples' => [['word' => '安い', 'reading' => 'やすい', 'meaning' => 'N5.kanji_data.k75.ex1_meaning'], ['word' => '安心', 'reading' => 'あんしん', 'meaning' => 'N5.kanji_data.k75.ex2_meaning']]],
                ['character' => '新', 'sino_vietnamese' => 'N5.kanji_data.k76.sino', 'meaning' => 'N5.kanji_data.k76.meaning', 'onyomi' => ['シン'], 'kunyomi' => ['あたら.しい'], 'stroke_count' => 13, 'mnemonic' => 'N5.kanji_data.k76.mnemonic', 'examples' => [['word' => '新しい', 'reading' => 'あたらしい', 'meaning' => 'N5.kanji_data.k76.ex1_meaning'], ['word' => '新聞', 'reading' => 'しんぶん', 'meaning' => 'N5.kanji_data.k76.ex2_meaning']]],
                ['character' => '古', 'sino_vietnamese' => 'N5.kanji_data.k77.sino', 'meaning' => 'N5.kanji_data.k77.meaning', 'onyomi' => ['コ'], 'kunyomi' => ['ふる.い'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k77.mnemonic', 'examples' => [['word' => '古い', 'reading' => 'ふるい', 'meaning' => 'N5.kanji_data.k77.ex1_meaning'], ['word' => '中古', 'reading' => 'ちゅうこ', 'meaning' => 'N5.kanji_data.k77.ex2_meaning']]],
                ['character' => '長', 'sino_vietnamese' => 'N5.kanji_data.k78.sino', 'meaning' => 'N5.kanji_data.k78.meaning', 'onyomi' => ['チョウ'], 'kunyomi' => ['なが.い'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k78.mnemonic', 'examples' => [['word' => '長い', 'reading' => 'ながい', 'meaning' => 'N5.kanji_data.k78.ex1_meaning'], ['word' => '社長', 'reading' => 'しゃちょう', 'meaning' => 'N5.kanji_data.k78.ex2_meaning']]],
                ['character' => '南', 'sino_vietnamese' => 'N5.kanji_data.k79.sino', 'meaning' => 'N5.kanji_data.k79.meaning', 'onyomi' => ['ナン', 'ナ'], 'kunyomi' => ['みなみ'], 'stroke_count' => 9, 'mnemonic' => 'N5.kanji_data.k79.mnemonic', 'examples' => [['word' => '南', 'reading' => 'みなみ', 'meaning' => 'N5.kanji_data.k79.ex1_meaning'], ['word' => '東南アジア', 'reading' => 'とうなんアジア', 'meaning' => 'N5.kanji_data.k79.ex2_meaning']]],
                ['character' => '北', 'sino_vietnamese' => 'N5.kanji_data.k80.sino', 'meaning' => 'N5.kanji_data.k80.meaning', 'onyomi' => ['ホク'], 'kunyomi' => ['きた'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k80.mnemonic', 'examples' => [['word' => '北', 'reading' => 'きた', 'meaning' => 'N5.kanji_data.k80.ex1_meaning'], ['word' => '北海道', 'reading' => 'ほっかいどう', 'meaning' => 'N5.kanji_data.k80.ex2_meaning']]],
                ['character' => '何', 'sino_vietnamese' => 'N5.kanji_data.k81.sino', 'meaning' => 'N5.kanji_data.k81.meaning', 'onyomi' => ['カ'], 'kunyomi' => ['なに', 'なん'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k81.mnemonic', 'examples' => [['word' => '何', 'reading' => 'なに', 'meaning' => 'N5.kanji_data.k81.ex1_meaning'], ['word' => '何人', 'reading' => 'なんにん', 'meaning' => 'N5.kanji_data.k81.ex2_meaning']]],
            ],
            $lessonModels[9]->id => [
                ['character' => '行', 'sino_vietnamese' => 'N5.kanji_data.k82.sino', 'meaning' => 'N5.kanji_data.k82.meaning', 'onyomi' => ['コウ', 'ギョウ', 'アン'], 'kunyomi' => ['い.く', 'ゆ.く', 'おこな.う'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k82.mnemonic', 'examples' => [['word' => '行く', 'reading' => 'いく', 'meaning' => 'N5.kanji_data.k82.ex1_meaning'], ['word' => '旅行', 'reading' => 'りょこう', 'meaning' => 'N5.kanji_data.k82.ex2_meaning']]],
                ['character' => '来', 'sino_vietnamese' => 'N5.kanji_data.k83.sino', 'meaning' => 'N5.kanji_data.k83.meaning', 'onyomi' => ['ライ'], 'kunyomi' => ['く.る', 'きた.る', 'き', 'こ'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k83.mnemonic', 'examples' => [['word' => '来る', 'reading' => 'くる', 'meaning' => 'N5.kanji_data.k83.ex1_meaning'], ['word' => '来年', 'reading' => 'らいねん', 'meaning' => 'N5.kanji_data.k83.ex2_meaning']]],
                ['character' => '休', 'sino_vietnamese' => 'N5.kanji_data.k84.sino', 'meaning' => 'N5.kanji_data.k84.meaning', 'onyomi' => ['キュウ'], 'kunyomi' => ['やす.む', 'やす.み'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k84.mnemonic', 'examples' => [['word' => '休む', 'reading' => 'やすむ', 'meaning' => 'N5.kanji_data.k84.ex1_meaning'], ['word' => '夏休み', 'reading' => 'なつやすみ', 'meaning' => 'N5.kanji_data.k84.ex2_meaning']]],
                ['character' => '食', 'sino_vietnamese' => 'N5.kanji_data.k85.sino', 'meaning' => 'N5.kanji_data.k85.meaning', 'onyomi' => ['ショク', 'ジキ'], 'kunyomi' => ['く.う', 'く.らう', 'た.べる'], 'stroke_count' => 9, 'mnemonic' => 'N5.kanji_data.k85.mnemonic', 'examples' => [['word' => '食べる', 'reading' => 'たべる', 'meaning' => 'N5.kanji_data.k85.ex1_meaning'], ['word' => '食堂', 'reading' => 'しょくどう', 'meaning' => 'N5.kanji_data.k85.ex2_meaning']]],
                ['character' => '飲', 'sino_vietnamese' => 'N5.kanji_data.k86.sino', 'meaning' => 'N5.kanji_data.k86.meaning', 'onyomi' => ['イン'], 'kunyomi' => ['の.む'], 'stroke_count' => 12, 'mnemonic' => 'N5.kanji_data.k86.mnemonic', 'examples' => [['word' => '飲む', 'reading' => 'のむ', 'meaning' => 'N5.kanji_data.k86.ex1_meaning'], ['word' => '飲み物', 'reading' => 'のみもの', 'meaning' => 'N5.kanji_data.k86.ex2_meaning']]],
                ['character' => '立', 'sino_vietnamese' => 'N5.kanji_data.k87.sino', 'meaning' => 'N5.kanji_data.k87.meaning', 'onyomi' => ['リツ', 'リュウ'], 'kunyomi' => ['た.つ', 'た.てる'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k87.mnemonic', 'examples' => [['word' => '立つ', 'reading' => 'たつ', 'meaning' => 'N5.kanji_data.k87.ex1_meaning'], ['word' => '国立', 'reading' => 'こくりつ', 'meaning' => 'N5.kanji_data.k87.ex2_meaning']]],
                ['character' => '出', 'sino_vietnamese' => 'N5.kanji_data.k88.sino', 'meaning' => 'N5.kanji_data.k88.meaning', 'onyomi' => ['シュツ', 'スイ'], 'kunyomi' => ['で.る', 'だ.す'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k88.mnemonic', 'examples' => [['word' => '出る', 'reading' => 'でる', 'meaning' => 'N5.kanji_data.k88.ex1_meaning'], ['word' => '出口', 'reading' => 'でぐち', 'meaning' => 'N5.kanji_data.k88.ex2_meaning']]],
                ['character' => '入', 'sino_vietnamese' => 'N5.kanji_data.k89.sino', 'meaning' => 'N5.kanji_data.k89.meaning', 'onyomi' => ['ニュウ'], 'kunyomi' => ['い.る', 'い.れる', 'はい.る'], 'stroke_count' => 2, 'mnemonic' => 'N5.kanji_data.k89.mnemonic', 'examples' => [['word' => '入る', 'reading' => 'はいる', 'meaning' => 'N5.kanji_data.k89.ex1_meaning'], ['word' => '入口', 'reading' => 'いりぐち', 'meaning' => 'N5.kanji_data.k89.ex2_meaning']]],
                ['character' => '買', 'sino_vietnamese' => 'N5.kanji_data.k90.sino', 'meaning' => 'N5.kanji_data.k90.meaning', 'onyomi' => ['バイ'], 'kunyomi' => ['か.う'], 'stroke_count' => 12, 'mnemonic' => 'N5.kanji_data.k90.mnemonic', 'examples' => [['word' => '買う', 'reading' => 'かう', 'meaning' => 'N5.kanji_data.k90.ex1_meaning'], ['word' => '買い物', 'reading' => 'かいもの', 'meaning' => 'N5.kanji_data.k90.ex2_meaning']]],
                ['character' => '読', 'sino_vietnamese' => 'N5.kanji_data.k91.sino', 'meaning' => 'N5.kanji_data.k91.meaning', 'onyomi' => ['ドク', 'トク', 'トウ'], 'kunyomi' => ['よ.む'], 'stroke_count' => 14, 'mnemonic' => 'N5.kanji_data.k91.mnemonic', 'examples' => [['word' => '読む', 'reading' => 'よむ', 'meaning' => 'N5.kanji_data.k91.ex1_meaning'], ['word' => '読書', 'reading' => 'どくしょ', 'meaning' => 'N5.kanji_data.k91.ex2_meaning']]],
                ['character' => '書', 'sino_vietnamese' => 'N5.kanji_data.k92.sino', 'meaning' => 'N5.kanji_data.k92.meaning', 'onyomi' => ['ショ'], 'kunyomi' => ['か.く'], 'stroke_count' => 10, 'mnemonic' => 'N5.kanji_data.k92.mnemonic', 'examples' => [['word' => '書く', 'reading' => 'かく', 'meaning' => 'N5.kanji_data.k92.ex1_meaning'], ['word' => '図書館', 'reading' => 'としょかん', 'meaning' => 'N5.kanji_data.k92.ex2_meaning']]],
            ],
            $lessonModels[10]->id => [
                ['character' => '学', 'sino_vietnamese' => 'N5.kanji_data.k93.sino', 'meaning' => 'N5.kanji_data.k93.meaning', 'onyomi' => ['ガク'], 'kunyomi' => ['まな.ぶ'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k93.mnemonic', 'examples' => [['word' => '学生', 'reading' => 'がくせい', 'meaning' => 'N5.kanji_data.k93.ex1_meaning'], ['word' => '学校', 'reading' => 'がっこう', 'meaning' => 'N5.kanji_data.k93.ex2_meaning']]],
                ['character' => '校', 'sino_vietnamese' => 'N5.kanji_data.k94.sino', 'meaning' => 'N5.kanji_data.k94.meaning', 'onyomi' => ['コウ', 'キョウ'], 'kunyomi' => [], 'stroke_count' => 10, 'mnemonic' => 'N5.kanji_data.k94.mnemonic', 'examples' => [['word' => '学校', 'reading' => 'がっこう', 'meaning' => 'N5.kanji_data.k94.ex1_meaning'], ['word' => '校長', 'reading' => 'こうちょう', 'meaning' => 'N5.kanji_data.k94.ex2_meaning']]],
                ['character' => '本', 'sino_vietnamese' => 'N5.kanji_data.k95.sino', 'meaning' => 'N5.kanji_data.k95.meaning', 'onyomi' => ['ホン'], 'kunyomi' => ['もと'], 'stroke_count' => 5, 'mnemonic' => 'N5.kanji_data.k95.mnemonic', 'examples' => [['word' => '本', 'reading' => 'ほん', 'meaning' => 'N5.kanji_data.k95.ex1_meaning'], ['word' => '日本', 'reading' => 'にほん', 'meaning' => 'N5.kanji_data.k95.ex2_meaning']]],
                ['character' => '名', 'sino_vietnamese' => 'N5.kanji_data.k96.sino', 'meaning' => 'N5.kanji_data.k96.meaning', 'onyomi' => ['メイ', 'ミョウ'], 'kunyomi' => ['な'], 'stroke_count' => 6, 'mnemonic' => 'N5.kanji_data.k96.mnemonic', 'examples' => [['word' => '名前', 'reading' => 'なまえ', 'meaning' => 'N5.kanji_data.k96.ex1_meaning'], ['word' => '有名', 'reading' => 'ゆうめい', 'meaning' => 'N5.kanji_data.k96.ex2_meaning']]],
                ['character' => '語', 'sino_vietnamese' => 'N5.kanji_data.k97.sino', 'meaning' => 'N5.kanji_data.k97.meaning', 'onyomi' => ['ゴ'], 'kunyomi' => ['かた.る', 'かた.らう'], 'stroke_count' => 14, 'mnemonic' => 'N5.kanji_data.k97.mnemonic', 'examples' => [['word' => '日本語', 'reading' => 'にほんご', 'meaning' => 'N5.kanji_data.k97.ex1_meaning'], ['word' => '英語', 'reading' => 'えいご', 'meaning' => 'N5.kanji_data.k97.ex2_meaning']]],
                ['character' => '間', 'sino_vietnamese' => 'N5.kanji_data.k98.sino', 'meaning' => 'N5.kanji_data.k98.meaning', 'onyomi' => ['カン', 'ケン'], 'kunyomi' => ['あいだ', 'ま'], 'stroke_count' => 12, 'mnemonic' => 'N5.kanji_data.k98.mnemonic', 'examples' => [['word' => '間', 'reading' => 'あいだ', 'meaning' => 'N5.kanji_data.k98.ex1_meaning'], ['word' => '時間', 'reading' => 'じかん', 'meaning' => 'N5.kanji_data.k98.ex2_meaning']]],
                ['character' => '電', 'sino_vietnamese' => 'N5.kanji_data.k99.sino', 'meaning' => 'N5.kanji_data.k99.meaning', 'onyomi' => ['デン'], 'kunyomi' => [], 'stroke_count' => 13, 'mnemonic' => 'N5.kanji_data.k99.mnemonic', 'examples' => [['word' => '電車', 'reading' => 'でんしゃ', 'meaning' => 'N5.kanji_data.k99.ex1_meaning'], ['word' => '電話', 'reading' => 'でんわ', 'meaning' => 'N5.kanji_data.k99.ex2_meaning']]],
                ['character' => '車', 'sino_vietnamese' => 'N5.kanji_data.k100.sino', 'meaning' => 'N5.kanji_data.k100.meaning', 'onyomi' => ['シャ'], 'kunyomi' => ['くるま'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k100.mnemonic', 'examples' => [['word' => '車', 'reading' => 'くるま', 'meaning' => 'N5.kanji_data.k100.ex1_meaning'], ['word' => '自転車', 'reading' => 'じてんしゃ', 'meaning' => 'N5.kanji_data.k100.ex2_meaning']]],
                ['character' => '門', 'sino_vietnamese' => 'N5.kanji_data.k101.sino', 'meaning' => 'N5.kanji_data.k101.meaning', 'onyomi' => ['モン'], 'kunyomi' => ['かど'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k101.mnemonic', 'examples' => [['word' => '門', 'reading' => 'もん', 'meaning' => 'N5.kanji_data.k101.ex1_meaning'], ['word' => '専門', 'reading' => 'せんもん', 'meaning' => 'N5.kanji_data.k101.ex2_meaning']]],
                ['character' => '駅', 'sino_vietnamese' => 'N5.kanji_data.k102.sino', 'meaning' => 'N5.kanji_data.k102.meaning', 'onyomi' => ['エキ'], 'kunyomi' => [], 'stroke_count' => 14, 'mnemonic' => 'N5.kanji_data.k102.mnemonic', 'examples' => [['word' => '駅', 'reading' => 'えき', 'meaning' => 'N5.kanji_data.k102.ex1_meaning'], ['word' => '駅前', 'reading' => 'えきまえ', 'meaning' => 'N5.kanji_data.k102.ex2_meaning']]],
                ['character' => '社', 'sino_vietnamese' => 'N5.kanji_data.k103.sino', 'meaning' => 'N5.kanji_data.k103.meaning', 'onyomi' => ['シャ'], 'kunyomi' => ['やしろ'], 'stroke_count' => 7, 'mnemonic' => 'N5.kanji_data.k103.mnemonic', 'examples' => [['word' => '会社', 'reading' => 'かいしゃ', 'meaning' => 'N5.kanji_data.k103.ex1_meaning'], ['word' => '社会', 'reading' => 'しゃかい', 'meaning' => 'N5.kanji_data.k103.ex2_meaning']]],
                ['character' => '店', 'sino_vietnamese' => 'N5.kanji_data.k104.sino', 'meaning' => 'N5.kanji_data.k104.meaning', 'onyomi' => ['テン'], 'kunyomi' => ['みせ'], 'stroke_count' => 8, 'mnemonic' => 'N5.kanji_data.k104.mnemonic', 'examples' => [['word' => '店', 'reading' => 'みせ', 'meaning' => 'N5.kanji_data.k104.ex1_meaning'], ['word' => '喫茶店', 'reading' => 'きっさてん', 'meaning' => 'N5.kanji_data.k104.ex2_meaning']]],
            ],
        ];

        foreach ($kanjiLessons as $lessonId => $kanjis) {
            foreach ($kanjis as $kData) {
                $kanji = Kanji::firstOrCreate(
                    [
                        'character' => $kData['character'],
                        'lesson_id' => $lessonId
                    ],
                    [
                        'sino_vietnamese' => $kData['sino_vietnamese'],
                        'meaning' => $kData['meaning'],
                        'onyomi' => $kData['onyomi'],
                        'kunyomi' => $kData['kunyomi'],
                        'stroke_count' => $kData['stroke_count'],
                        'mnemonic' => $kData['mnemonic'],
                        'jlpt_level' => 'N5'
                    ]
                );

                // Create and associate vocabulary cards specific to this Kanji
                if (!empty($kData['examples'])) {
                    $cardIds = [];
                    foreach ($kData['examples'] as $ex) {
                        $vocabCard = Card::firstOrCreate(
                            [
                                'lesson_id' => $lessonId, // Grouping the vocab with the Kanji's lesson
                                'type' => 'vocabulary',
                                'front_text' => $ex['word']
                            ],
                            [
                                'back_text' => $ex['meaning'],
                                'reading' => $ex['reading'] ?? null,
                                'example_japanese' => null,
                                'example_blocks_json' => null
                            ]
                        );
                        $cardIds[] = $vocabCard->id;
                    }
                    if (!empty($cardIds)) {
                        $kanji->cards()->syncWithoutDetaching($cardIds);
                    }
                }
                
                // Create a Flashcard specific for the Kanji itself
                $kanjiCard = Card::firstOrCreate(
                    [
                        'lesson_id' => $lessonId,
                        'type' => 'kanji',
                        'front_text' => $kanji->character,
                    ],
                    [
                        'back_text' => $kanji->sino_vietnamese . ' - ' . $kanji->meaning,
                        'example_japanese' => null,
                        'example_blocks_json' => null
                    ]
                );
                $kanji->cards()->syncWithoutDetaching([$kanjiCard->id]);
            }
        }

        $this->command->info("Kanji data seeded successfully!");
    }
}
