<?php

namespace App\Console\Commands;

use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Redis;

class ResetWeeklyLeagueCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:reset-weekly-league';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Reset the weekly leaderboard and award ranks';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting weekly league reset...');

        // Get last week's key
        $lastWeek = Carbon::now()->subWeek()->format('Y_W');
        $leaderboardKey = "leaderboard:weekly:{$lastWeek}";

        if (Redis::exists($leaderboardKey)) {
            // Ideally we would snapshot this or distribute rewards.
            // For now, we just acknowledge it.
            $topUsers = Redis::zrevrange($leaderboardKey, 0, 9, 'WITHSCORES');
            
            // Could insert into a `leaderboard_history` table here

            // Optionally set expiration on old leaderboard so it cleans up automatically
            Redis::expire($leaderboardKey, 86400 * 30); // keep for 30 days
            
            $this->info("Archived leaderboard for week {$lastWeek}. Top users: " . count($topUsers));
        } else {
            $this->info("No leaderboard found for week {$lastWeek}.");
        }

        // The current week's leaderboard is automatically generated by Redis when zincrby is called,
        // so no explicit creation is needed.

        $this->info('Weekly league reset complete.');
    }
}
